require 'spec_helper'

describe package('keepalived') do
  it { should be_installed }
end

describe file('/etc/keepalived/conf.d') do
  it { should be_directory }
end

describe file('/etc/keepalived/keepalived.conf') do
  it { should be_file }
  it { should contain 'This file autogenerated by Chef' }
end

describe service('keepalived') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/keepalived/conf.d/script_test.conf') do
  it { should be_file }
  it { should contain 'This file autogenerated by Chef' }
  it { should contain 'vrrp_script test' }
  it { should contain 'script "/bin/true"' }
end

describe file('/etc/keepalived/conf.d/test.conf') do
  it { should_not be_file }
end

describe file('/etc/keepalived/conf.d/vrrp_test.conf') do
  it { should be_file }
  it { should contain 'This file autogenerated by Chef' }
  it { should contain 'vrrp_instance TEST' }
  it { should contain 'interface eth0' }
  it { should contain '127.0.1.1' }
end

describe interface('eth0') do
  it { should have_ipv4_address('127.0.1.1') }
end

describe file('/etc/keepalived/conf.d/vs_test.conf') do
  it { should be_file }
  it { should contain 'This file autogenerated by Chef' }
  it { should contain 'virtual_server 127.0.0.1 443' }
  it { should contain 'real_server 127.0.2.1 443' }
  it { should contain 'real_server 127.0.2.2 443' }
end
